<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260319131352 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_alerts_status');
        $this->addSql('DROP INDEX idx_alerts_created_at');
        $this->addSql('ALTER TABLE alerts ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE alerts ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE alerts ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_alerts_user_id RENAME TO IDX_F77AC06BA76ED395');
        $this->addSql('ALTER INDEX idx_alerts_detection_id RENAME TO IDX_F77AC06BA8773B17');
        $this->addSql('DROP INDEX idx_users_email');
        $this->addSql('DROP INDEX idx_users_created_at');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE users ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER INDEX users_email_key RENAME TO UNIQ_1483A5E9E7927C74');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA storage');
        $this->addSql('CREATE SCHEMA auth');
        $this->addSql('CREATE SCHEMA graphql');
        $this->addSql('CREATE SCHEMA graphql_public');
        $this->addSql('CREATE SCHEMA vault');
        $this->addSql('CREATE SCHEMA realtime');
        $this->addSql('CREATE SCHEMA pgbouncer');
        $this->addSql('CREATE SCHEMA extensions');
        $this->addSql('ALTER TABLE alerts ALTER id SET DEFAULT nextval(\'alerts_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE alerts ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE alerts ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('CREATE INDEX idx_alerts_status ON alerts (status)');
        $this->addSql('CREATE INDEX idx_alerts_created_at ON alerts (created_at)');
        $this->addSql('ALTER INDEX idx_f77ac06ba8773b17 RENAME TO idx_alerts_detection_id');
        $this->addSql('ALTER INDEX idx_f77ac06ba76ed395 RENAME TO idx_alerts_user_id');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE users ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('CREATE INDEX idx_users_email ON users (email)');
        $this->addSql('CREATE INDEX idx_users_created_at ON users (created_at)');
        $this->addSql('ALTER INDEX uniq_1483a5e9e7927c74 RENAME TO users_email_key');
    }
}
